#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>
#include "../include/apidisk.h"
#include "../include/bitmap2.h"
#include "../include/auxiliar.h"
#include "../include/files.h"
#include "../include/t2fs.h"
#include "../include/MFT_list.h"
#include "../include/MFT.h"
#include "../include/directories.h"


int main(int argc, char *argv[])
{
	init();

	char buffer[] = " TESTANDO TESTANDO TESTANDO TESTANDO TESTANDO TESTANDO TESTANDO TESTANDO TESTANDO TESTANDO TESTANDO TESTANDO TESTANDO TESTANDO TESTANDO TESTANDO TESTANDO TESTANDO TESTANDO TESTANDO TESTANDO TESTANDO TESTANDO TESTANDO TESTANDO TESTANDO TESTANDO TESTANDO TESTANDO TESTANDO TESTANDO TESTANDO TESTANDO TESTANDO TESTANDO TESTANDO TESTANDO TESTANDO TESTANDO TESTANDO TESTANDO TESTANDO TESTANDO TESTANDO TESTANDO TESTANDO TESTANDO TESTANDO TESTANDO TESTANDO TESTANDO TESTANDO TESTANDO TESTANDO TESTANDO TESTANDO TESTANDO TESTANDO TESTANDO TESTANDO TESTANDO TESTANDO TESTANDO TESTANDO TESTANDO TESTANDO TESTANDO TESTANDO TESTANDO TESTANDO TESTANDO TESTANDO TESTANDO TESTANDO TESTANDO TESTANDO TESTANDO TESTANDO TESTANDO TESTANDO TESTANDO TESTANDO TESTANDO TESTANDO TESTANDO TESTANDO TESTANDO TESTANDO TESTANDO TESTANDO TESTANDO TESTANDO TESTANDO TESTANDO TESTANDO TESTANDO TESTANDO TESTANDO TESTANDO TESTANDO TESTANDO TESTANDO TESTANDO TESTANDO TESTANDO TESTANDO TESTANDO TESTANDO TESTANDO TESTANDO TESTANDO TESTANDO TESTANDO TESTAN NEW_BLOCK NEW_BLOCK NEW_BLOCK NEW_BLOCK NEW_BLOCK NEW_BLOCK NEW_BLOCK NEW_BLOCK NEW_BLOCK NEW_BLOCK NEW_BLOCK NEW_BLOCK NEW_BLOCK NEW_BLOCK NEW_BLOCK NEW_BLOCK NEW_BLOCK NEW_BLOCK NEW_BLOCK NEW_BLOCK NEW_BLOCK NEW_BLOCK NEW_BLOCK NEW_BLOCK NEW_BLOCK NEW_BLOCK NEW_BLOCK NEW_BLOCK NEW_BLOCK NEW_BLOCK NEW_BLOCK NEW_BLOCK NEW_BLOCK NEW_BLOCK NEW_BLOCK NEW_BLOCK NEW_BLOCK NEW_BLOCK NEW_BLOCK NEW_BLOCK NEW_BLOCK NEW_BLOCK NEW_BLOCK NEW_BLOCK NEW_BLOCK NEW_BLOCK NEW_BLOCK NEW_BLOCK NEW_BLOCK NEW_BLOCK NEW_BLOCK NEW_BLOCK NEW_BLOCK NEW_BLOCK NEW_BLOCK NEW_BLOCK NEW_BLOCK NEW_BLOCK NEW_BLOCK NEW_BLOCK NEW_BLOCK NEW_BLOCK NEW_BLOCK NEW_BLOCK NEW_BLOCK NEW_BLOCK NEW_BLOCK NEW_BLOCK NEW_BLOCK NEW_BLOCK NEW_BLOCK NEW_BLOCK NEW_BLOCK NEW_BLOCK NEW_BLOCK NEW_BLOCK NEW_BLOCK NEW_BLOCK NEW_BLOCK NEW_BLOCK NEW_BLOCK NEW_BLOCK NEW_BLOCK NEW_BLOCK NEW_BLOCK NEW_BLOCK NEW_BLOCK NEW_BLOCK NEW_BLOCK NEW_BLOCK NEW_BLOCK NEW_BLOCK NEW_BLOCK NEW_BLOCK NEW_BLOCK NEW_BLOCK NEW_BLOCK NEW_BLOCK NEW_BLOCK NEW_BLOCK NEW_BLOCK NEW_BLOCK NEW SPOILERS SPOILERS";

	char file[] = "/file1";


return 0;
}

