#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>
#include "../include/apidisk.h"
#include "../include/bitmap2.h"
#include "../include/auxiliar.h"
#include "../include/files.h"
#include "../include/t2fs.h"
#include "../include/MFT_list.h"
#include "../include/MFT.h"
#include "../include/directories.h"

#define ATRIB_TYPE 0
#define VBN 4
#define LBN 8
#define CONTIG_BLOCK 12

#define TUPLE_ATRTYPE 0 
#define TUPLE_VBN 4
#define TUPLE_LBN 8
#define TUPLE_NUMCONTIGBLOCK 12

int main(int argc, char *argv[])
{
	init();

	char buffer[] = " TESTANDO TESTANDO TESTANDO TESTANDO TESTANDO TESTANDO TESTANDO TESTANDO TESTANDO TESTANDO TESTANDO TESTANDO TESTANDO TESTANDO TESTANDO TESTANDO TESTANDO TESTANDO TESTANDO TESTANDO TESTANDO TESTANDO TESTANDO TESTANDO TESTANDO TESTANDO TESTANDO TESTANDO TESTANDO TESTANDO TESTANDO TESTANDO TESTANDO TESTANDO TESTANDO TESTANDO TESTANDO TESTANDO TESTANDO TESTANDO TESTANDO TESTANDO TESTANDO TESTANDO TESTANDO TESTANDO TESTANDO TESTANDO TESTANDO TESTANDO TESTANDO TESTANDO TESTANDO TESTANDO TESTANDO TESTANDO TESTANDO TESTANDO TESTANDO TESTANDO TESTANDO TESTANDO TESTANDO TESTANDO TESTANDO TESTANDO TESTANDO TESTANDO TESTANDO TESTANDO TESTANDO TESTANDO TESTANDO TESTANDO TESTANDO TESTANDO TESTANDO TESTANDO TESTANDO TESTANDO TESTANDO TESTANDO TESTANDO TESTANDO TESTANDO TESTANDO TESTANDO TESTANDO TESTANDO TESTANDO TESTANDO TESTANDO TESTANDO TESTANDO TESTANDO TESTANDO TESTANDO TESTANDO TESTANDO TESTANDO TESTANDO TESTANDO TESTANDO TESTANDO TESTANDO TESTANDO TESTANDO TESTANDO TESTANDO TESTANDO TESTANDO TESTANDO TESTANDO TESTAN NEW_BLOCK NEW_BLOCK NEW_BLOCK NEW_BLOCK NEW_BLOCK NEW_BLOCK NEW_BLOCK NEW_BLOCK NEW_BLOCK NEW_BLOCK NEW_BLOCK NEW_BLOCK NEW_BLOCK NEW_BLOCK NEW_BLOCK NEW_BLOCK NEW_BLOCK NEW_BLOCK NEW_BLOCK NEW_BLOCK NEW_BLOCK NEW_BLOCK NEW_BLOCK NEW_BLOCK NEW_BLOCK NEW_BLOCK NEW_BLOCK NEW_BLOCK NEW_BLOCK NEW_BLOCK NEW_BLOCK NEW_BLOCK NEW_BLOCK NEW_BLOCK NEW_BLOCK NEW_BLOCK NEW_BLOCK NEW_BLOCK NEW_BLOCK NEW_BLOCK NEW_BLOCK NEW_BLOCK NEW_BLOCK NEW_BLOCK NEW_BLOCK NEW_BLOCK NEW_BLOCK NEW_BLOCK NEW_BLOCK NEW_BLOCK NEW_BLOCK NEW_BLOCK NEW_BLOCK NEW_BLOCK NEW_BLOCK NEW_BLOCK NEW_BLOCK NEW_BLOCK NEW_BLOCK NEW_BLOCK NEW_BLOCK NEW_BLOCK NEW_BLOCK NEW_BLOCK NEW_BLOCK NEW_BLOCK NEW_BLOCK NEW_BLOCK NEW_BLOCK NEW_BLOCK NEW_BLOCK NEW_BLOCK NEW_BLOCK NEW_BLOCK NEW_BLOCK NEW_BLOCK NEW_BLOCK NEW_BLOCK NEW_BLOCK NEW_BLOCK NEW_BLOCK NEW_BLOCK NEW_BLOCK NEW_BLOCK NEW_BLOCK NEW_BLOCK NEW_BLOCK NEW_BLOCK NEW_BLOCK NEW_BLOCK NEW_BLOCK NEW_BLOCK NEW_BLOCK NEW_BLOCK NEW_BLOCK NEW_BLOCK NEW_BLOCK NEW_BLOCK NEW_BLOCK NEW_BLOCK NEW_BLOCK NEW_BLOCK NEW SPOILERS SPOILERS";

	char file[] = "/file1";


	int j = open2(file);
	printf ("%d IT WORKED", j);
	printf ("%s asdasdf\n", opened_files[0].file_path);



	write2(0, buffer, 2066);
	return 0;

}

